# Generated by Django 5.1.2 on 2024-10-26 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Accno', models.IntegerField()),
                ('Adharno', models.IntegerField()),
                ('DoB', models.DateField()),
                ('Branch', models.CharField(max_length=20)),
            ],
        ),
    ]
